#!/usr/bin/env python3
"""Генератор JS-файла из канонического KPI display JSON.

Запуск:  python sidecar/econometrica/tools/sync_kpi_display.py
Проверка: python sidecar/econometrica/tools/sync_kpi_display.py --check
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).parent.parent.parent.parent  # корень проекта
_JSON_PATH = Path(__file__).parent.parent / "data" / "kpi_display_registry.json"
_OUT_PATH = _ROOT / "src" / "lib" / "kpi" / "kpi-display.generated.js"


def _js_value(v, indent: int = 0) -> str:
    r"""Сериализует Python-значение в JS-литерал (кириллица без \uXXXX)."""
    pad = " " * indent
    inner_pad = " " * (indent + 2)
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        escaped = v.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(v, list):
        items = [f"{inner_pad}{_js_value(item)}" for item in v]
        return "[\n" + ",\n".join(items) + f"\n{pad}]"
    if isinstance(v, dict):
        lines = []
        for k, val in v.items():
            lines.append(f"{inner_pad}{_js_value(k)}: {_js_value(val, indent + 2)}")
        return "{\n" + ",\n".join(lines) + f"\n{pad}}}"
    raise TypeError(f"Неподдерживаемый тип: {type(v)}")


def generate(data: dict) -> str:
    """Генерирует содержимое JS-файла из данных реестра."""
    lines = [
        "// GENERATED by sidecar/econometrica/tools/sync_kpi_display.py — DO NOT EDIT.",
        "// Источник истины: sidecar/econometrica/data/kpi_display_registry.json",
        "",
    ]

    # KPI_DISPLAY_CURRENCY
    currency = data["currency"]
    currency_js = _js_value(currency, 0)
    lines.append(f"export const KPI_DISPLAY_CURRENCY = {currency_js};")
    lines.append("")

    # KPI_DISPLAY
    kpi_map = data["kpi"]
    kpi_lines = []
    for kpi_type, kpi_data in kpi_map.items():
        kpi_value = _js_value(kpi_data, 2)
        kpi_lines.append(f'  "{kpi_type}": {kpi_value}')
    kpi_body = ",\n".join(kpi_lines)
    lines.append(f"export const KPI_DISPLAY = {{\n{kpi_body}\n}};")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="Проверяет дрейф без перезаписи файла")
    args = parser.parse_args()

    with open(_JSON_PATH, encoding="utf-8") as f:
        data = json.load(f)

    content = generate(data)

    if args.check:
        if _OUT_PATH.exists():
            existing = _OUT_PATH.read_text(encoding="utf-8")
            if existing == content:
                print("OK")
                sys.exit(0)
            else:
                print("DRIFT")
                sys.exit(1)
        else:
            print("DRIFT")
            sys.exit(1)

    _OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUT_PATH.write_text(content, encoding="utf-8")
    print(f"written: {_OUT_PATH}")


if __name__ == "__main__":
    main()
