"""
engines.channel_action - single source of truth для PRESCRIPTIVE action labels.

Promoted from narrative_adapter.derive_verdict (math-fix v1.4, 2026-04-28) so HTML
+ PPTX templates consume one consistent recommendation per channel - no more
«Hold verdict in table» vs «явный потенциал scale-up в commentary» contradictions
exposed by Kagocel live-test 2026-04-27.

DUAL-VERDICT-SYSTEM doctrine (audit-of-audit B1 finding):
  • DESCRIPTIVE state - past performance label («Перенасыщен», «Эффективен» и т.д.)
    derived from ROI + efficiency_gap. Generated by `decomposer.compute_roi_verdict`.
    Used in Декомпозиция UI page table.
  • PRESCRIPTIVE action - future direction label («Масштабировать», «Сократить»)
    derived from mROAS + optimizer redistribution + CI uncertainty. Generated
    HERE. Used by HTML/PPTX action table + commentary + findings.

Both могут coexist: канал с descriptive='Перенасыщен' (high ROI + small gap)
honest получит prescriptive=Hold (mROAS ~ 1.0, optimizer не двигает). Эти ARE
two separate business questions and should be answered independently.

Vocabulary (5 actions + 1 uncertain):
  Scale     - нарастить (mROAS ≥ 1.2 + optimizer ratio ≥ 1.05 OR mROAS ≥ 1.5 + gap ≥ +5pp)
  Hold      - удерживать (mROAS ≥ 1.0, gap stable, optimizer ratio ≈ 1.0)
  Watch     - мониторить (нет clear signal - between Hold и Reduce/Cut)
  Reduce    - сократить умеренно (saturation-bound: mROAS 0.8-1.0 OR optimizer ratio ≤ 0.95)
  Cut       - сократить (mROAS < 0.8: бюджет приносит убыток)
  Uncertain - недостаточно данных (CI width > mROAS OR untrained channel)

Public API:
  ACTION_KEYS         - 6-tuple of canonical keys
  ACTION_LABEL_RU     - RU label per key
  ACTION_TONE         - tone (good/warn/bad/neutral) per key
  ACTION_PRIORITY     - sort priority per key (Scale=5, Hold=4, ..., Cut=0)
  compute_channel_action(channel_dict) → ChannelAction
  build_action_summary(channels) → dict с counts + top_by_action_list
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


ACTION_KEYS: tuple[str, ...] = ('Scale', 'Hold', 'Watch', 'Reduce', 'Cut', 'Uncertain')

ACTION_LABEL_RU: dict[str, str] = {
    'Scale':     'Масштабировать',
    'Hold':      'Удерживать',
    'Watch':     'Под наблюдением',
    'Reduce':    'Сократить умеренно',
    'Cut':       'Сократить',
    'Uncertain': 'Недостаточно данных',
}

ACTION_TONE: dict[str, str] = {
    'Scale':     'good',
    'Hold':      'good',
    'Watch':     'neutral',
    'Reduce':    'warn',
    'Cut':       'bad',
    'Uncertain': 'warn',
}

# Sort priority - Scale highest (most actionable), Cut lowest.
ACTION_PRIORITY: dict[str, int] = {
    'Scale':     5,
    'Hold':      4,
    'Watch':     2,
    'Reduce':    1,
    'Cut':       0,
    'Uncertain': 3,  # mid - needs human review, не automatic action
}


# Волна 1 пункт 3 (2026-06-20): краткий отображаемый вердикт-действие для ТАБЛИЦ
# отчётов (HTML badge / PPTX action table / XLSX / MD). Единый рус-источник —
# прежде HTML и Rust (XLSX/MD) показывали англ. machine-key «Scale», а PPTX свой
# verdict_ru «Увеличить» → один канал выглядел по-разному в трёх форматах.
VERDICT_DISPLAY_RU: dict[str, str] = {
    'Scale':     'Увеличить',
    'Hold':      'Держать',
    'Watch':     'Наблюдать',
    'Reduce':    'Сократить',
    'Cut':       'Остановить',
    'Uncertain': 'Недостаточно данных',
}


def soften_verdict_display(verdict_key: str, reliability_verdict: str | None) -> tuple[str, str]:
    """Honesty-потолок (решение 2a, Антон): глобальная надёжность модели смягчает
    ДИРЕКТИВНОСТЬ канального вердикта по МОДАЛЬНОСТИ, сохраняя НАПРАВЛЕНИЕ.

    Снимает противоречие «канал Scale в отчёте vs Uncertain в декомпозиции»: при
    неуверенной модели ни один канал не подаётся как директива к масштабированию.

    Returns (label, modality):
      • reliable / нет вердикта → директивный label («Увеличить»), modality 'firm'
      • uncertain / unknown → label + « (предв.)» («Увеличить (предв.)»), modality
        'tentative'; нейтральные Watch/Uncertain — без суффикса (уже неуверенные)
      • unreliable → «Требует переобучения», modality 'refused' (модель не сошлась —
        направление ненадёжно, не показываем; согласуется с гейтом M2 refused)
    """
    base = VERDICT_DISPLAY_RU.get(verdict_key, verdict_key)
    rv = (reliability_verdict or '').lower()
    if rv == 'unreliable':
        return ('Требует переобучения', 'refused')
    if rv in ('uncertain', 'unknown'):
        if verdict_key in ('Uncertain', 'Watch'):
            return (base, 'tentative')
        return (f'{base} (предв.)', 'tentative')
    return (base, 'firm')


@dataclass(frozen=True)
class ChannelAction:
    """Result of compute_channel_action - what to do with this channel."""
    key: str            # one of ACTION_KEYS
    label_ru: str       # human-readable Russian
    tone: str           # 'good' / 'warn' / 'bad' / 'neutral'
    reasoning: str      # 1-line explanation for tooltips/footnotes
    priority: int       # для sort
    confidence: str     # 'high' / 'medium' / 'low' - based on CI width


def compute_channel_action(channel: dict[str, Any]) -> ChannelAction:
    """Single source of truth для prescriptive action label.

    Reads from a merged channel dict (output of narrative_adapter._merge_channels).
    Expected keys (all optional - missing → conservative fallback):
        mroas:                   marginal ROAS (point estimate)
        mroas_ci_low/high:       posterior 90% CI bounds (optional)
        avg_roi or roi:          average ROI (descriptive fallback when mROAS missing)
        current_spend:           native units (or money - relative ratio used only)
        optimal_spend:           optimizer recommendation
        efficiency_gap:          contribution_share - spend_share (пп)
        untrained:               True if channel had zero training variance
        spend:                   total spend (for zero-spend detection)

    Decision tree (top to bottom - first match wins):
      1. Untrained channel                            → Uncertain (neutral tone)
      2. Zero spend                                   → Uncertain (canal не в портфеле)
      3. CI uncertainty (width > |mROAS|)             → Uncertain
      4. mROAS < 0.8                                  → Cut
      5. Optimizer says optimal/current ≤ 0.95        → Reduce (signal from optimizer)
      6. mROAS < 1.0 (near breakeven)                 → Reduce
      7. Optimizer says optimal/current ≥ 1.05 + mROAS ≥ 1.0 → Scale (optimizer agrees)
      8. mROAS ≥ 1.5 AND gap ≥ +5pp                   → Scale (under-invested signal)
      9. mROAS ≥ 1.0 AND |gap| < 5pp                  → Hold (balanced)
      10. else                                        → Watch
    """
    # ─ Inputs ─────────────────────────────────────────────────────────
    # Track parse failures + missing-info для bad-data fallback (Watch вместо Uncertain).
    parse_failures = 0
    mroas_explicit = any(
        channel.get(k) is not None for k in ('mroas', 'avg_roi', 'roi')
    )
    mroas_raw = channel.get('mroas')
    if mroas_raw is None:
        mroas_raw = channel.get('avg_roi') or channel.get('roi') or 0.0
    try:
        mroas = float(mroas_raw)
    except (TypeError, ValueError):
        mroas = 0.0
        parse_failures += 1

    spend_raw = channel.get('current_spend') or channel.get('spend') or 0.0
    try:
        cur_spend = float(spend_raw)
    except (TypeError, ValueError):
        cur_spend = 0.0
        parse_failures += 1

    opt_raw = channel.get('optimal_spend')
    try:
        opt_spend = float(opt_raw) if opt_raw is not None else cur_spend
    except (TypeError, ValueError):
        opt_spend = cur_spend
        parse_failures += 1

    # Bad-data fallback: когда mROAS отсутствует И spend unparseable → Watch
    # (не Uncertain - Uncertain reserved для CI / untrained / explicit signal).
    bad_input = (
        not mroas_explicit
        and parse_failures >= 1
        and not channel.get('untrained')
    )

    eff_gap_raw = channel.get('efficiency_gap')
    try:
        eff_gap = float(eff_gap_raw) if eff_gap_raw is not None else 0.0
    except (TypeError, ValueError):
        eff_gap = 0.0

    ratio = (opt_spend / cur_spend) if cur_spend > 1e-9 else 1.0

    # CI inputs - Phase 1.9 posterior. None for v1.0/v1.1 pickles.
    ci_low_raw = channel.get('mroas_ci_low')
    ci_high_raw = channel.get('mroas_ci_high')
    try:
        ci_low = float(ci_low_raw) if ci_low_raw is not None else None
        ci_high = float(ci_high_raw) if ci_high_raw is not None else None
    except (TypeError, ValueError):
        ci_low = ci_high = None
    has_ci = ci_low is not None and ci_high is not None
    ci_width = (ci_high - ci_low) if has_ci else None
    confidence = 'high' if has_ci and ci_width is not None and ci_width < abs(mroas) * 0.5 else (
        'medium' if has_ci and ci_width is not None and ci_width < abs(mroas) else 'low'
    )

    # ─ Decision tree ──────────────────────────────────────────────────

    # 0. Bad input fallback (preserves backward compat с derive_verdict)
    if bad_input:
        return ChannelAction(
            key='Watch',
            label_ru=ACTION_LABEL_RU['Watch'],
            tone='neutral',
            reasoning='Недостаточно данных для оценки - канал требует проверки',
            priority=ACTION_PRIORITY['Watch'],
            confidence='low',
        )

    # 1. Untrained - нет варианса в обучающих данных
    if channel.get('untrained'):
        return ChannelAction(
            key='Uncertain',
            label_ru=ACTION_LABEL_RU['Uncertain'],
            tone=ACTION_TONE['Uncertain'],
            reasoning='Канал не обучен - нулевая вариативность в тренировочных данных',
            priority=ACTION_PRIORITY['Uncertain'],
            confidence='low',
        )

    # 2. Zero spend - отсутствует в текущем портфеле
    if cur_spend <= 1e-9:
        return ChannelAction(
            key='Uncertain',
            label_ru=ACTION_LABEL_RU['Uncertain'],
            tone='neutral',
            reasoning='Канал не получает бюджет в текущем портфеле - оценка невозможна',
            priority=ACTION_PRIORITY['Uncertain'],
            confidence='low',
        )

    # 3. Severe optimizer cut signal - Cut (regardless of mROAS).
    # Backward compat: derive_verdict treated ratio < 0.5 as Cut even при positive mROAS -
    # это explicit «удалить канал» signal от optimizer (e.g. при money-mode redistribution
    # бюджет ушёл к другим channels с гораздо лучшим mROAS).
    if cur_spend > 1e-9 and ratio < 0.5:
        return ChannelAction(
            key='Cut',
            label_ru=ACTION_LABEL_RU['Cut'],
            tone=ACTION_TONE['Cut'],
            reasoning=(
                f'Optimizer рекомендует -{(1 - ratio) * 100:.0f}% - '
                f'бюджет лучше использовать на других каналах'
            ),
            priority=ACTION_PRIORITY['Cut'],
            confidence=confidence,
        )

    # 5. Below breakeven - Cut
    if mroas > 0 and mroas < 0.8:
        return ChannelAction(
            key='Cut',
            label_ru=ACTION_LABEL_RU['Cut'],
            tone=ACTION_TONE['Cut'],
            reasoning=f'mROAS {mroas:.2f}× глубоко ниже breakeven - каждый рубль приносит убыток',
            priority=ACTION_PRIORITY['Cut'],
            confidence=confidence,
        )

    # 6. Optimizer recommends moderate reduction - Reduce (даже если mROAS > 1.0, saturation-bound)
    if ratio <= 0.95 and mroas >= 1.0:
        return ChannelAction(
            key='Reduce',
            label_ru=ACTION_LABEL_RU['Reduce'],
            tone=ACTION_TONE['Reduce'],
            reasoning=(
                f'Optimizer рекомендует {(ratio - 1) * 100:+.0f}% - saturation, '
                f'mROAS {mroas:.2f}× падает с ростом вложения'
            ),
            priority=ACTION_PRIORITY['Reduce'],
            confidence=confidence,
        )

    # 6. Near breakeven - Reduce
    if mroas > 0 and mroas < 1.0:
        return ChannelAction(
            key='Reduce',
            label_ru=ACTION_LABEL_RU['Reduce'],
            tone=ACTION_TONE['Reduce'],
            reasoning=f'mROAS {mroas:.2f}× близок к breakeven - снизить риск',
            priority=ACTION_PRIORITY['Reduce'],
            confidence=confidence,
        )

    # 7. Optimizer recommends growth - Scale (signal из optimizer'а сильнее эвристики)
    if ratio >= 1.05 and mroas >= 1.0:
        return ChannelAction(
            key='Scale',
            label_ru=ACTION_LABEL_RU['Scale'],
            tone=ACTION_TONE['Scale'],
            reasoning=(
                f'Optimizer рекомендует +{(ratio - 1) * 100:.0f}%, mROAS {mroas:.2f}× - '
                f'недо-инвестирован'
            ),
            priority=ACTION_PRIORITY['Scale'],
            confidence=confidence,
        )

    # 8. mROAS+gap heuristic для Scale (когда optimizer не двигает, но gap signal)
    if mroas >= 1.5 and eff_gap >= 5.0:
        return ChannelAction(
            key='Scale',
            label_ru=ACTION_LABEL_RU['Scale'],
            tone=ACTION_TONE['Scale'],
            reasoning=(
                f'mROAS {mroas:.2f}×, gap +{eff_gap:.0f}пп - канал даёт больше эффекта '
                f'чем доли бюджета'
            ),
            priority=ACTION_PRIORITY['Scale'],
            confidence=confidence,
        )

    # 9. CI uncertainty - оценивается ПОСЛЕ optimizer signals.
    # Rationale: optimizer's redistribution implicitly integrates over joint
    # posterior (mROAS samples per channel), так что его рекомендация (ratio
    # значительно ≠ 1) уже отражает ranked confidence даже когда individual
    # CI на канал wide. Только когда optimizer не двигает + CI wide → Uncertain.
    # Без этого ordering: small N → wide CI → ВСЕ каналы Uncertain даже когда
    # optimizer нашёл clear +28% redistribution (Kagocel case).
    if has_ci and ci_width is not None and mroas > 0 and ci_width > mroas:
        return ChannelAction(
            key='Uncertain',
            label_ru=ACTION_LABEL_RU['Uncertain'],
            tone=ACTION_TONE['Uncertain'],
            reasoning=(
                f'CI [{ci_low:.2f}-{ci_high:.2f}] шире чем mROAS {mroas:.2f}×, '
                f'оптимизатор не предложил перераспределения - '
                f'нужно больше данных для уверенной рекомендации'
            ),
            priority=ACTION_PRIORITY['Uncertain'],
            confidence='low',
        )

    # 10. Hold - стабильный, mROAS заметно выше breakeven (>1.1), gap не явный.
    # Threshold tightened от 1.0 к 1.1 - mROAS=1.0 ровно на breakeven, не Hold.
    if mroas >= 1.1 and abs(eff_gap) < 5.0:
        return ChannelAction(
            key='Hold',
            label_ru=ACTION_LABEL_RU['Hold'],
            tone=ACTION_TONE['Hold'],
            reasoning=f'mROAS {mroas:.2f}× стабилен, gap {eff_gap:+.0f}пп - баланс',
            priority=ACTION_PRIORITY['Hold'],
            confidence=confidence,
        )

    # 10. Watch - fallback (mROAS ≈ breakeven OR gap большой, нет optimizer signal)
    return ChannelAction(
        key='Watch',
        label_ru=ACTION_LABEL_RU['Watch'],
        tone=ACTION_TONE['Watch'],
        reasoning=f'mROAS {mroas:.2f}×, gap {eff_gap:+.0f}пп - нужен мониторинг',
        priority=ACTION_PRIORITY['Watch'],
        confidence=confidence,
    )


def build_action_summary(channels: list[dict[str, Any]]) -> dict[str, Any]:
    """Compute portfolio-level action counts + top-by-action lists.

    Used by narrative_adapter._derive_narrative_facts → strings_ru templates.

    Returns:
        {
            'counts': {'Scale': N, 'Hold': N, 'Watch': N, 'Reduce': N, 'Cut': N, 'Uncertain': N},
            'channels_by_action': {'Scale': [name1, name2, ...], ...},
            'top_action': str  # most-frequent prescriptive action (excl. Watch/Uncertain)
        }
    """
    counts = {key: 0 for key in ACTION_KEYS}
    channels_by_action: dict[str, list[str]] = {key: [] for key in ACTION_KEYS}

    for ch in channels or []:
        action_key = ch.get('action') if isinstance(ch.get('action'), str) else None
        if action_key not in ACTION_KEYS:
            # Compute on-the-fly если не populated upstream
            action_key = compute_channel_action(ch).key
        counts[action_key] = counts.get(action_key, 0) + 1
        name = ch.get('name')
        if name:
            channels_by_action[action_key].append(name)

    # Top action - most-frequent decisive action (excludes Watch/Uncertain как «неясно»)
    decisive = {k: v for k, v in counts.items() if k not in ('Watch', 'Uncertain')}
    top_action = max(decisive.items(), key=lambda kv: kv[1])[0] if decisive and max(decisive.values()) > 0 else 'Watch'

    return {
        'counts': counts,
        'channels_by_action': channels_by_action,
        'top_action': top_action,
    }
