"""
engines.channel_action - single source of truth для PRESCRIPTIVE action labels.

Promoted from narrative_adapter.derive_verdict (math-fix v1.4, 2026-04-28) so HTML
+ PPTX templates consume one consistent recommendation per channel - no more
«Hold verdict in table» vs «явный потенциал scale-up в commentary» contradictions
exposed by Kagocel live-test 2026-04-27.

DUAL-VERDICT-SYSTEM doctrine (audit-of-audit B1 finding):
  • DESCRIPTIVE state - past performance label («Перенасыщен», «Эффективен» и т.д.)
    derived from ROI + efficiency_gap. Generated by `decomposer.compute_roi_verdict`.
    Used in Декомпозиция UI page table.
  • PRESCRIPTIVE action - future direction label («Масштабировать», «Сократить»)
    derived from mROAS + optimizer redistribution + CI uncertainty. Generated
    HERE. Used by HTML/PPTX action table + commentary + findings.

Both могут coexist: канал с descriptive='Перенасыщен' (high ROI + small gap)
honest получит prescriptive=Hold (mROAS ~ 1.0, optimizer не двигает). Эти ARE
two separate business questions and should be answered independently.

Vocabulary (5 actions + 1 uncertain):
  Scale     - нарастить (mROAS ≥ 1.2 + optimizer ratio ≥ 1.05 OR mROAS ≥ 1.5 + gap ≥ +5pp)
  Hold      - удерживать (mROAS ≥ 1.0, gap stable, optimizer ratio ≈ 1.0)
  Watch     - мониторить (нет clear signal - between Hold и Reduce/Cut)
  Reduce    - сократить умеренно (saturation-bound: mROAS 0.8-1.0 OR optimizer ratio ≤ 0.95)
  Cut       - сократить (mROAS < 0.8: бюджет приносит убыток)
  Uncertain - недостаточно данных (CI width > mROAS OR untrained channel)

Public API:
  ACTION_KEYS         - 6-tuple of canonical keys
  ACTION_LABEL_RU     - RU label per key
  ACTION_TONE         - tone (good/warn/bad/neutral) per key
  ACTION_PRIORITY     - sort priority per key (Scale=5, Hold=4, ..., Cut=0)
  VERDICT_DISPLAY_RU  - краткий рус-вердикт для табличных ячеек отчётов
  soften_verdict_display(verdict_key, reliability_verdict) → (label, modality) -
                         honesty-потолок: смягчает директивность по надёжности модели
  compute_channel_action(channel_dict, *, kpi_kind, vpcu, money_roi_unavailable,
                         metric_short, cpu_per_label) → ChannelAction
  build_action_summary(channels) → dict с counts + top_by_action_list

KPI-паспорт (Фаза 3, пласт 1 — 2026-07-11):
  Для СЧЁТНОЙ метрики (лиды/упаковки) mROAS = units/₽ ≈ 0.01–0.05.
  Абсолютные пороги 0.8/1.0/1.5 неприменимы к count-метрике напрямую.
  Честное поведение:
    • count + vpcu > 0:  eff_mroas = mroas * vpcu; decision-tree по eff_mroas.
    • count без vpcu (money_roi_unavailable=True): деградация — только optimizer-сигнал.
      CPU = 1/mroas отображается в reasoning, пользователю предлагается задать ценность.
    • monetary: поведение без изменений (backward-compat).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


ACTION_KEYS: tuple[str, ...] = ('Scale', 'Hold', 'Watch', 'Reduce', 'Cut', 'Uncertain')

ACTION_LABEL_RU: dict[str, str] = {
    'Scale':     'Масштабировать',
    'Hold':      'Удерживать',
    'Watch':     'Под наблюдением',
    'Reduce':    'Сократить умеренно',
    'Cut':       'Сократить',
    'Uncertain': 'Недостаточно данных',
}

ACTION_TONE: dict[str, str] = {
    'Scale':     'good',
    'Hold':      'good',
    'Watch':     'neutral',
    'Reduce':    'warn',
    'Cut':       'bad',
    'Uncertain': 'warn',
}

# Sort priority - Scale highest (most actionable), Cut lowest.
ACTION_PRIORITY: dict[str, int] = {
    'Scale':     5,
    'Hold':      4,
    'Watch':     2,
    'Reduce':    1,
    'Cut':       0,
    'Uncertain': 3,  # mid - needs human review, не automatic action
}


# Волна 1 пункт 3 (2026-06-20, перенесено 2026-08-04): краткий отображаемый
# вердикт-действие для ТАБЛИЦ отчётов (HTML badge / PPTX action table). Единый
# рус-источник — прежде HTML/PPTX могли показывать один канал по-разному в
# разных форматах.
VERDICT_DISPLAY_RU: dict[str, str] = {
    'Scale':     'Увеличить',
    'Hold':      'Держать',
    'Watch':     'Наблюдать',
    'Reduce':    'Сократить',
    'Cut':       'Остановить',
    'Uncertain': 'Недостаточно данных',
}


def soften_verdict_display(verdict_key: str, reliability_verdict: str | None) -> tuple[str, str]:
    """Honesty-потолок (решение 2a, Антон): глобальная надёжность модели смягчает
    ДИРЕКТИВНОСТЬ канального вердикта по МОДАЛЬНОСТИ, сохраняя НАПРАВЛЕНИЕ.

    Снимает противоречие «канал Scale в отчёте vs Uncertain в декомпозиции»: при
    неуверенной модели ни один канал не подаётся как директива к масштабированию.

    Returns (label, modality):
      • reliable / нет вердикта → директивный label («Увеличить»), modality 'firm'
      • uncertain / unknown → label + « (предв.)» («Увеличить (предв.)»), modality
        'tentative'; нейтральные Watch/Uncertain — без суффикса (уже неуверенные)
      • unreliable → «Требует переобучения», modality 'refused' (модель не сошлась —
        направление ненадёжно, не показываем; согласуется с гейтом M2 refused)
    """
    base = VERDICT_DISPLAY_RU.get(verdict_key, verdict_key)
    rv = (reliability_verdict or '').lower()
    if rv == 'unreliable':
        return ('Требует переобучения', 'refused')
    if rv in ('uncertain', 'unknown'):
        if verdict_key in ('Uncertain', 'Watch'):
            return (base, 'tentative')
        return (f'{base} (предв.)', 'tentative')
    return (base, 'firm')


@dataclass(frozen=True)
class ChannelAction:
    """Result of compute_channel_action - what to do with this channel."""
    key: str            # one of ACTION_KEYS
    label_ru: str       # human-readable Russian
    tone: str           # 'good' / 'warn' / 'bad' / 'neutral'
    reasoning: str      # 1-line explanation for tooltips/footnotes
    priority: int       # для sort
    confidence: str     # 'high' / 'medium' / 'low' - based on CI width


def _metric_phrase(
    mroas: float,
    kpi_kind: str,
    vpcu: float | None,
    metric_short: str,
    cpu_per_label: str,
) -> str:
    """Паспорт-aware строка для reasoning-сообщений.

    monetary  → '1.23×'
    count+vpcu → 'CPU 456 ₽/лид'
    count без vpcu → 'CPU 456 ₽/лид (ценность единицы не задана)'
    """
    if kpi_kind != 'count':
        return f'{mroas:.2f}×'
    # Для count метрика ВСЕГДА CPU — не полагаемся на metric_short (его дефолт 'ROI'
    # при прямом вызове дал бы противоречие «ROI ₽/лид»; аудит 2026-07-11).
    if mroas > 0:
        cpu = 1.0 / mroas
        cpu_fmt = f'{cpu:.0f}' if cpu >= 10 else f'{cpu:.1f}'
        base = f'CPU {cpu_fmt} {cpu_per_label}'
    else:
        base = f'CPU — {cpu_per_label}'
    if vpcu is None or vpcu <= 0:
        return f'{base} (ценность единицы не задана)'
    return base


def compute_channel_action(
    channel: dict[str, Any],
    *,
    kpi_kind: str = 'monetary',
    vpcu: float | None = None,
    money_roi_unavailable: bool = False,
    metric_short: str = 'ROI',
    cpu_per_label: str = '₽/ед.',
) -> ChannelAction:
    """Single source of truth для prescriptive action label.

    Reads from a merged channel dict (output of narrative_adapter._merge_channels).
    Expected keys (all optional - missing → conservative fallback):
        mroas:                   marginal ROAS (point estimate)
        mroas_ci_low/high:       posterior 90% CI bounds (optional)
        avg_roi or roi:          average ROI (descriptive fallback when mROAS missing)
        current_spend:           native units (or money - relative ratio used only)
        optimal_spend:           optimizer recommendation
        efficiency_gap:          contribution_share - spend_share (пп)
        untrained:               True if channel had zero training variance
        spend:                   total spend (for zero-spend detection)

    KPI kwargs (Фаза 3, пласт 1):
        kpi_kind:              'monetary' | 'count'
        vpcu:                  value_per_count_unit (₽/единица); None = не задана
        money_roi_unavailable: True когда count-KPI без vpcu или derived_mode='effectiveness'
        metric_short:          'ROI' | 'CPU' | 'Доля' — короткое название метрики
        cpu_per_label:         '₽/лид' / '₽/упак.' / '₽/ед.' — единица CPU

    Decision tree (top to bottom - first match wins):
      1. Untrained channel                            → Uncertain (neutral tone)
      2. Zero spend                                   → Uncertain (canal не в портфеле)
      3. CI uncertainty (width > |eff_mroas|)         → Uncertain
      4. eff_mroas < 0.8                              → Cut
      5. Optimizer says optimal/current ≤ 0.95        → Reduce (signal from optimizer)
      6. eff_mroas < 1.0 (near breakeven)             → Reduce
      7. Optimizer says optimal/current ≥ 1.05 + eff_mroas ≥ 1.0 → Scale
      8. eff_mroas ≥ 1.5 AND gap ≥ +5pp               → Scale
      9. eff_mroas ≥ 1.0 AND |gap| < 5pp              → Hold
      10. else                                        → Watch

    При money_roi_unavailable=True (count без vpcu):
      Абсолютные breakeven-пороги (шаги 4, 6, 7, 8) НЕ применяются.
      Только optimizer-сигнал: ratio ≤ 0.95 → Reduce; ≥ 1.05 → Scale; → Watch.
    """
    # ─ Inputs ─────────────────────────────────────────────────────────
    # Track parse failures + missing-info для bad-data fallback (Watch вместо Uncertain).
    parse_failures = 0
    mroas_explicit = any(
        channel.get(k) is not None for k in ('mroas', 'avg_roi', 'roi')
    )
    mroas_raw = channel.get('mroas')
    if mroas_raw is None:
        mroas_raw = channel.get('avg_roi') or channel.get('roi') or 0.0
    try:
        mroas = float(mroas_raw)
    except (TypeError, ValueError):
        mroas = 0.0
        parse_failures += 1

    spend_raw = channel.get('current_spend') or channel.get('spend') or 0.0
    try:
        cur_spend = float(spend_raw)
    except (TypeError, ValueError):
        cur_spend = 0.0
        parse_failures += 1

    opt_raw = channel.get('optimal_spend')
    try:
        opt_spend = float(opt_raw) if opt_raw is not None else cur_spend
    except (TypeError, ValueError):
        opt_spend = cur_spend
        parse_failures += 1

    # Bad-data fallback: когда mROAS отсутствует И spend unparseable → Watch
    # (не Uncertain - Uncertain reserved для CI / untrained / explicit signal).
    bad_input = (
        not mroas_explicit
        and parse_failures >= 1
        and not channel.get('untrained')
    )

    eff_gap_raw = channel.get('efficiency_gap')
    try:
        eff_gap = float(eff_gap_raw) if eff_gap_raw is not None else 0.0
    except (TypeError, ValueError):
        eff_gap = 0.0

    ratio = (opt_spend / cur_spend) if cur_spend > 1e-9 else 1.0

    # CI inputs - Phase 1.9 posterior. None for v1.0/v1.1 pickles.
    ci_low_raw = channel.get('mroas_ci_low')
    ci_high_raw = channel.get('mroas_ci_high')
    try:
        ci_low = float(ci_low_raw) if ci_low_raw is not None else None
        ci_high = float(ci_high_raw) if ci_high_raw is not None else None
    except (TypeError, ValueError):
        ci_low = ci_high = None
    has_ci = ci_low is not None and ci_high is not None
    ci_width = (ci_high - ci_low) if has_ci else None

    # KPI-паспорт: вычисляем eff_mroas — то значение, которое прогоняется через
    # decision-tree для breakeven/scale/hold порогов.
    # monetary:        eff_mroas == mroas (без изменений)
    # count + vpcu>0:  eff_mroas = mroas * vpcu  (переводим units/₽ → ₽/₽-эквивалент)
    # count без vpcu:  eff_mroas НЕ используется для абсолютных breakeven-порогов
    #                  (money_roi_unavailable=True → деградация к optimizer-only)
    _vpcu_valid = (kpi_kind == 'count') and isinstance(vpcu, (int, float)) and vpcu > 0
    if _vpcu_valid:
        eff_mroas = mroas * vpcu
    else:
        eff_mroas = mroas

    # CI confidence рассчитывается по eff_mroas для корректной relative оценки
    confidence = 'high' if has_ci and ci_width is not None and ci_width < abs(eff_mroas) * 0.5 else (
        'medium' if has_ci and ci_width is not None and ci_width < abs(eff_mroas) else 'low'
    )

    # ─ Decision tree ──────────────────────────────────────────────────

    # 0. Bad input fallback (preserves backward compat с derive_verdict)
    if bad_input:
        return ChannelAction(
            key='Watch',
            label_ru=ACTION_LABEL_RU['Watch'],
            tone='neutral',
            reasoning='Недостаточно данных для оценки - канал требует проверки',
            priority=ACTION_PRIORITY['Watch'],
            confidence='low',
        )

    # 1. Untrained - нет варианса в обучающих данных
    if channel.get('untrained'):
        return ChannelAction(
            key='Uncertain',
            label_ru=ACTION_LABEL_RU['Uncertain'],
            tone=ACTION_TONE['Uncertain'],
            reasoning='Канал не обучен - нулевая вариативность в тренировочных данных',
            priority=ACTION_PRIORITY['Uncertain'],
            confidence='low',
        )

    # 2. Zero spend - отсутствует в текущем портфеле
    if cur_spend <= 1e-9:
        return ChannelAction(
            key='Uncertain',
            label_ru=ACTION_LABEL_RU['Uncertain'],
            tone='neutral',
            reasoning='Канал не получает бюджет в текущем портфеле - оценка невозможна',
            priority=ACTION_PRIORITY['Uncertain'],
            confidence='low',
        )

    # 3. Severe optimizer cut signal - Cut (regardless of mROAS / eff_mroas).
    # Backward compat: derive_verdict treated ratio < 0.5 as Cut even при positive mROAS -
    # это explicit «удалить канал» signal от optimizer (e.g. при money-mode redistribution
    # бюджет ушёл к другим channels с гораздо лучшим mROAS).
    # NB: этот шаг применяется и при money_roi_unavailable — optimizer-сигнал всегда валиден.
    if cur_spend > 1e-9 and ratio < 0.5:
        return ChannelAction(
            key='Cut',
            label_ru=ACTION_LABEL_RU['Cut'],
            tone=ACTION_TONE['Cut'],
            reasoning=(
                f'Оптимизатор рекомендует -{(1 - ratio) * 100:.0f}% - '
                f'бюджет лучше использовать на других каналах'
            ),
            priority=ACTION_PRIORITY['Cut'],
            confidence=confidence,
        )

    # ─ Деградация: count без vpcu (money_roi_unavailable) ─────────────
    # Абсолютные breakeven-пороги (4, 6, 7, 8) НЕ применяются: mROAS семантически
    # несопоставим с порогами ₽/₽. Оставляем только optimizer-сигнал.
    if money_roi_unavailable:
        _metric_str = _metric_phrase(mroas, kpi_kind, vpcu, metric_short, cpu_per_label)
        if ratio <= 0.95:
            return ChannelAction(
                key='Reduce',
                label_ru=ACTION_LABEL_RU['Reduce'],
                tone=ACTION_TONE['Reduce'],
                reasoning=(
                    f'{_metric_str}; Оптимизатор рекомендует {(ratio - 1) * 100:+.0f}% - '
                    f'задайте ценность единицы для оценки окупаемости'
                ),
                priority=ACTION_PRIORITY['Reduce'],
                confidence=confidence,
            )
        if ratio >= 1.05:
            return ChannelAction(
                key='Scale',
                label_ru=ACTION_LABEL_RU['Scale'],
                tone=ACTION_TONE['Scale'],
                reasoning=(
                    f'{_metric_str}; Оптимизатор рекомендует +{(ratio - 1) * 100:.0f}% - '
                    f'задайте ценность единицы для оценки окупаемости'
                ),
                priority=ACTION_PRIORITY['Scale'],
                confidence=confidence,
            )
        return ChannelAction(
            key='Watch',
            label_ru=ACTION_LABEL_RU['Watch'],
            tone=ACTION_TONE['Watch'],
            reasoning=(
                f'{_metric_str}; задайте ценность единицы для оценки окупаемости'
            ),
            priority=ACTION_PRIORITY['Watch'],
            confidence=confidence,
        )

    # ─ Основная ветка (monetary ИЛИ count + vpcu) — decision-tree по eff_mroas ──

    # Строка для reasoning (паспорт-aware). ВАЖНО: CPU считается от СЫРОГО mroas
    # (units/₽ → ₽/ед. = 1/mroas), НЕ от eff_mroas: eff_mroas = mroas×vpcu нужен только
    # для порогов decision-tree ниже. Передача eff_mroas сюда занизила бы CPU в vpcu раз
    # (аудит 2026-07-11). Для monetary eff_mroas == mroas, поэтому ветка не затронута.
    _metric_str = _metric_phrase(mroas, kpi_kind, vpcu, metric_short, cpu_per_label)

    # 4/5. Below breakeven - Cut
    if eff_mroas > 0 and eff_mroas < 0.8:
        return ChannelAction(
            key='Cut',
            label_ru=ACTION_LABEL_RU['Cut'],
            tone=ACTION_TONE['Cut'],
            reasoning=f'{_metric_str} глубоко ниже точки безубыточности - каждый рубль приносит убыток',
            priority=ACTION_PRIORITY['Cut'],
            confidence=confidence,
        )

    # 6a. Optimizer recommends moderate reduction - Reduce (даже если eff_mroas > 1.0, saturation-bound)
    if ratio <= 0.95 and eff_mroas >= 1.0:
        return ChannelAction(
            key='Reduce',
            label_ru=ACTION_LABEL_RU['Reduce'],
            tone=ACTION_TONE['Reduce'],
            reasoning=(
                f'Оптимизатор рекомендует {(ratio - 1) * 100:+.0f}% - насыщение, '
                f'{_metric_str} падает с ростом вложения'
            ),
            priority=ACTION_PRIORITY['Reduce'],
            confidence=confidence,
        )

    # 6b. Near breakeven - Reduce
    if eff_mroas > 0 and eff_mroas < 1.0:
        return ChannelAction(
            key='Reduce',
            label_ru=ACTION_LABEL_RU['Reduce'],
            tone=ACTION_TONE['Reduce'],
            reasoning=f'{_metric_str} близко к точке безубыточности - снизить риск',
            priority=ACTION_PRIORITY['Reduce'],
            confidence=confidence,
        )

    # 7. Optimizer recommends growth - Scale (signal из optimizer'а сильнее эвристики)
    if ratio >= 1.05 and eff_mroas >= 1.0:
        return ChannelAction(
            key='Scale',
            label_ru=ACTION_LABEL_RU['Scale'],
            tone=ACTION_TONE['Scale'],
            reasoning=(
                f'Оптимизатор рекомендует +{(ratio - 1) * 100:.0f}%, {_metric_str} - '
                f'недо-инвестирован'
            ),
            priority=ACTION_PRIORITY['Scale'],
            confidence=confidence,
        )

    # 8. eff_mroas+gap heuristic для Scale (когда optimizer не двигает, но gap signal)
    if eff_mroas >= 1.5 and eff_gap >= 5.0:
        return ChannelAction(
            key='Scale',
            label_ru=ACTION_LABEL_RU['Scale'],
            tone=ACTION_TONE['Scale'],
            reasoning=(
                f'{_metric_str}, gap +{eff_gap:.0f}пп - канал даёт больше эффекта '
                f'чем доли бюджета'
            ),
            priority=ACTION_PRIORITY['Scale'],
            confidence=confidence,
        )

    # 9. CI uncertainty - оценивается ПОСЛЕ optimizer signals.
    # Rationale: optimizer's redistribution implicitly integrates over joint
    # posterior (mROAS samples per channel), так что его рекомендация (ratio
    # значительно ≠ 1) уже отражает ranked confidence даже когда individual
    # CI на канал wide. Только когда optimizer не двигает + CI wide → Uncertain.
    # Без этого ordering: small N → wide CI → ВСЕ каналы Uncertain даже когда
    # optimizer нашёл clear +28% redistribution (Kagocel case).
    if has_ci and ci_width is not None and eff_mroas > 0 and ci_width > eff_mroas:
        _ci_lo_eff = ci_low * vpcu if _vpcu_valid else ci_low
        _ci_hi_eff = ci_high * vpcu if _vpcu_valid else ci_high
        return ChannelAction(
            key='Uncertain',
            label_ru=ACTION_LABEL_RU['Uncertain'],
            tone=ACTION_TONE['Uncertain'],
            reasoning=(
                f'Диапазон [{_ci_lo_eff:.2f}-{_ci_hi_eff:.2f}] шире чем {_metric_str}, '
                f'оптимизатор не предложил перераспределения - '
                f'нужно больше данных для уверенной рекомендации'
            ),
            priority=ACTION_PRIORITY['Uncertain'],
            confidence='low',
        )

    # 10. Hold - стабильный, eff_mroas заметно выше breakeven (>1.1), gap не явный.
    # Threshold tightened от 1.0 к 1.1 - eff_mroas=1.0 ровно на breakeven, не Hold.
    if eff_mroas >= 1.1 and abs(eff_gap) < 5.0:
        return ChannelAction(
            key='Hold',
            label_ru=ACTION_LABEL_RU['Hold'],
            tone=ACTION_TONE['Hold'],
            reasoning=f'{_metric_str} стабилен, gap {eff_gap:+.0f}пп - баланс',
            priority=ACTION_PRIORITY['Hold'],
            confidence=confidence,
        )

    # 10. Watch - fallback (eff_mroas ≈ breakeven OR gap большой, нет optimizer signal)
    return ChannelAction(
        key='Watch',
        label_ru=ACTION_LABEL_RU['Watch'],
        tone=ACTION_TONE['Watch'],
        reasoning=f'{_metric_str}, gap {eff_gap:+.0f}пп - нужен мониторинг',
        priority=ACTION_PRIORITY['Watch'],
        confidence=confidence,
    )


def build_action_summary(channels: list[dict[str, Any]]) -> dict[str, Any]:
    """Compute portfolio-level action counts + top-by-action lists.

    Used by narrative_adapter._derive_narrative_facts → strings_ru templates.

    Returns:
        {
            'counts': {'Scale': N, 'Hold': N, 'Watch': N, 'Reduce': N, 'Cut': N, 'Uncertain': N},
            'channels_by_action': {'Scale': [name1, name2, ...], ...},
            'top_action': str  # most-frequent prescriptive action (excl. Watch/Uncertain)
        }
    """
    counts = {key: 0 for key in ACTION_KEYS}
    channels_by_action: dict[str, list[str]] = {key: [] for key in ACTION_KEYS}

    for ch in channels or []:
        action_key = ch.get('action') if isinstance(ch.get('action'), str) else None
        if action_key not in ACTION_KEYS:
            # Compute on-the-fly если не populated upstream
            action_key = compute_channel_action(ch).key
        counts[action_key] = counts.get(action_key, 0) + 1
        name = ch.get('name')
        if name:
            channels_by_action[action_key].append(name)

    # Top action - most-frequent decisive action (excludes Watch/Uncertain как «неясно»)
    decisive = {k: v for k, v in counts.items() if k not in ('Watch', 'Uncertain')}
    top_action = max(decisive.items(), key=lambda kv: kv[1])[0] if decisive and max(decisive.values()) > 0 else 'Watch'

    return {
        'counts': counts,
        'channels_by_action': channels_by_action,
        'top_action': top_action,
    }
