"""
aurora_pptx — client-ready PPTX deliverable generator for Aurora AI Econometrica.

Template-equivalent via code (python-pptx limitation: cannot create slide
masters programmatically). Each slide rendered from scratch with centralized
style helpers driven by tokens.json (generated → aurora_tokens.py).

Primary API:

    from econometrica.aurora_pptx import build_pptx
    prs = build_pptx(data=None, lang='ru')
    prs.save(output_path)

Architecture:
  - builder.py       : AuroraPPTXBuilder monolithic class (all layouts + primitives).
                       Port of finalized Standards/templates/build_wireframe.py.
                       Session 3: default Kagocel data hardcoded.
                       Session 4 (M4): parametrize via data dict.
  - aurora_tokens    : brand colors/fonts/sizes, generated from tokens.json.
                       Gitignored, regenerated by build_sidecar.py pre-step.
  - templates/       : blank_with_theme.pptx (placeholder for future theme-based
                       workflow; currently builder creates fresh Presentation).

Deprecated submodules (superseded by builder.py, scheduled for Session 4.5 cleanup):
  - tokens.py, master.py, typography.py, charts.py, i18n.py, layouts.py,
    strings_ru.json, strings_en.json. Early-session skeleton; functionality
    inlined into builder.py during Session 3 port.
"""

from __future__ import annotations

__version__ = "0.2.0"


def build_pptx(data=None, lang: str = "ru"):
    """Build a full client-ready 13-slide PPTX deliverable.

    Args:
        data: dict with report content. Session 3 pilot: default Kagocel data.
              Session 4 (M4 refactor): parametrized from Econometrica pipeline.
        lang: 'ru' (default) | 'en' (v1.0.12 scope)

    Returns:
        pptx.Presentation instance. Caller does .save(path).

    Usage:
        from econometrica.aurora_pptx import build_pptx
        prs = build_pptx(data=None, lang='ru')  # pilot: uses default data
        prs.save('output.pptx')
    """
    from .builder import AuroraPPTXBuilder
    builder = AuroraPPTXBuilder(data=data, lang=lang)
    return builder.build()
